# Generated by Django 5.1.6 on 2025-06-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
